sudo: required
services:
    - docker

before_install:
  - docker build -t michaelbabin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run michaelbabin/react-test yarn test --coverage

after_success:
  - docker build -t michaelbabin/multi-client ./client
  - docker build -t michaelbabin/multi-worker ./worker
  - docker build -t michaelbabin/multi-server ./server
  - docker build -t michaelbabin/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push michaelbabin/multi-client
  - docker push michaelbabin/multi-worker
  - docker push michaelbabin/multi-server
  - docker push michaelbabin/multi-nginx