sudo: required
services:
  - docker

before_install:
  - docker build -t michaelbabin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run michaelbabin/react-test yarn test --watchAll=false

after_success:
  - docker build -t michaelbabin/multi-client ./client
  - docker build -t michaelbabin/multi-worker ./worker
  - docker build -t michaelbabin/multi-server ./server
  - docker build -t michaelbabin/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push michaelbabin/multi-client
  - docker push michaelbabin/multi-worker
  - docker push michaelbabin/multi-server
  - docker push michaelbabin/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-688055245864
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
